spring:
  datasource:
    url: jdbc:postgresql://postgres:5432/events
    username: user
    password: pass
  jpa:
    hibernate:
      ddl-auto: validate
  rabbitmq:
    host: rabbitmq
    port: 5672
    username: guest
    password: guest

clickhouse:
  url: jdbc:clickhouse://clickhouse:8123/default?compress=0
  username: default
  password: ""
server:
  port: 8082
